title: My Awesome Site
description: A simple site to render Markdown files using Jekyll and GitHub Pages
baseurl: ""
url: "https://<username>.github.io"
theme: minima

# Build settings
markdown: kramdown